sudo: false
language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update
    - composer validate --no-check-all --ansi

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer test

after_script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer coveralls
